<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SkillEvaluation.Core\SkillEvaluation.Core.csproj" />
    <ProjectReference Include="..\SkillEvaluation.Onnx\SkillEvaluation.Onnx.csproj" />
  </ItemGroup>
</Project>
