#Requires -Version 7.0
[CmdletBinding()]
param(
    [string] $SkillsRoot = (Resolve-Path (Join-Path $PSScriptRoot '..' 'skills')).Path,
    [switch] $Apply
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

$startMarker = '<!-- portfolio-matrix:start -->'
$endMarker = '<!-- portfolio-matrix:end -->'
$catalogPath = Join-Path $SkillsRoot 'README.md'

function Get-SkillMetadata ([string] $skillPath) {
    $content = Get-Content -LiteralPath $skillPath -Raw
    $nameMatch = [regex]::Match($content, '(?m)^name:\s*(?<value>[^\r\n]+)\r?$')
    if (-not $nameMatch.Success) { throw "Could not parse name from $skillPath" }

    $metadata = @{}
    $insideMetadata = $false
    foreach ($line in ($content -split "\r?\n")) {
        if ($line -ceq 'metadata:') { $insideMetadata = $true; continue }
        if (-not $insideMetadata) { continue }
        if ($line -match '^\s+(?<key>[a-z][a-z-]*):\s*(?<value>.*)$') {
            $metadata[$Matches.key] = $Matches.value.Trim()
            continue
        }
        if ($line -match '^\S') { break }
    }

    [pscustomobject]@{
        Name = $nameMatch.Groups['value'].Value.Trim()
        Metadata = $metadata
    }
}

function Format-Relationship ([string] $value) {
    if ([string]::IsNullOrWhiteSpace($value) -or $value -eq 'none') { return '-' }
    return (@($value -split ',' | ForEach-Object { '`' + $_.Trim() + '`' }) -join ', ')
}

$records = @(Get-ChildItem -LiteralPath $SkillsRoot -Directory |
    Where-Object { Test-Path (Join-Path $_.FullName 'SKILL.md') } |
    Sort-Object Name |
    ForEach-Object { Get-SkillMetadata (Join-Path $_.FullName 'SKILL.md') })

$lines = @(
    $startMarker
    '<!-- Generated by tools/Update-SkillCatalog.ps1. Do not edit this block by hand. -->'
    '| Skill | Applicability | Binding | Risk | Maturity | Requires | Related |'
    '| ----- | ------------- | ------- | ---- | -------- | -------- | ------- |'
)
foreach ($record in $records) {
    $lines += "| [$($record.Name)](./$($record.Name)/SKILL.md) | ``$($record.Metadata.applicability)`` | ``$($record.Metadata.binding)`` | ``$($record.Metadata.risk)`` | ``$($record.Metadata.maturity)`` | $(Format-Relationship $record.Metadata.requires) | $(Format-Relationship $record.Metadata.related) |"
}
$lines += $endMarker
$expectedBlock = $lines -join "`n"

$catalog = Get-Content -LiteralPath $catalogPath -Raw
$startIndex = $catalog.IndexOf($startMarker, [System.StringComparison]::Ordinal)
$endIndex = $catalog.IndexOf($endMarker, [System.StringComparison]::Ordinal)

if ($startIndex -lt 0 -or $endIndex -lt $startIndex) {
    if (-not $Apply) {
        throw "Portfolio matrix markers are missing from $catalogPath. Run with -Apply."
    }
    $updated = $catalog.TrimEnd("`r", "`n") + "`n`n## Portfolio contract`n`n$expectedBlock`n"
}
else {
    $endIndex += $endMarker.Length
    $currentBlock = $catalog.Substring($startIndex, $endIndex - $startIndex) -replace "`r`n", "`n"
    if (-not $Apply) {
        if ($currentBlock -cne $expectedBlock) {
            throw "Portfolio matrix is stale. Run tools/Update-SkillCatalog.ps1 -Apply and commit the result."
        }
        Write-Host 'Skill portfolio matrix is current.'
        return
    }
    $updated = $catalog.Substring(0, $startIndex) + $expectedBlock + $catalog.Substring($endIndex)
}

$newline = if ($catalog.Contains("`r`n")) { "`r`n" } else { "`n" }
$updated = ($updated -replace "`r?`n", $newline)
[System.IO.File]::WriteAllText($catalogPath, $updated)
Write-Host "Updated $catalogPath."